-- Hosted PostgreSQL verification with synthetic Auth fixtures. No Auth HTTP login is exercised.
-- Every change, including fixtures and test deletions, is rolled back.
begin;
do $test$
declare
 a uuid := gen_random_uuid(); b uuid := gen_random_uuid(); sa uuid := gen_random_uuid(); sb uuid := gen_random_uuid();
 eid uuid := gen_random_uuid(); t timestamptz := date_trunc('day',now() at time zone 'UTC') at time zone 'UTC' + interval '1 second';
 base_day date; v jsonb; seen boolean; n integer; labels jsonb := '[]'::jsonb; month_xp integer;
begin
 if t > now()-interval '32 minutes' then t:=t-interval '1 day'; end if;
 base_day:=(t at time zone 'UTC')::date;
 insert into auth.users(id,aud,role,is_anonymous) values(a,'authenticated','authenticated',false),(b,'authenticated','authenticated',false);
 insert into auth.sessions(id,user_id) values(sa,a),(sb,b);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 v:=public.ritmo_save_profile('TxA_'||left(a::text,8),true);
 if not (v->>'ranking_enabled')::boolean then raise exception 'profile A failed'; end if;
 labels:=labels||jsonb_build_array('authenticated_profile_A');
 perform set_config('role','none',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 v:=public.ritmo_save_profile('TxB_'||left(b::text,8),true);
 labels:=labels||jsonb_build_array('authenticated_profile_B');
 perform set_config('role','none',true);
 update public.ritmo_profiles set enabled_at=now()-interval '40 days' where user_id in(a,b);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 v:=public.ritmo_submit_workout(eid,t,t+interval '60 seconds');
 if (v->>'xp')::integer<>100 then raise exception 'first XP'; end if;
 labels:=labels||jsonb_build_array('first_workout_100_XP');
 v:=public.ritmo_submit_workout(eid,t,t+interval '60 seconds');
 if not (v->>'duplicate')::boolean or (v->>'total_xp')::integer<>100 then raise exception 'duplicate'; end if;
 labels:=labels||jsonb_build_array('duplicate_UUID_idempotent');
 v:=public.ritmo_submit_workout(gen_random_uuid(),t+interval '3 minutes',t+interval '4 minutes');
 if (v->>'xp')::integer<>25 then raise exception 'second XP'; end if;
 labels:=labels||jsonb_build_array('second_workout_25_XP');
 for n in 2..10 loop
  v:=public.ritmo_submit_workout(gen_random_uuid(),t+n*interval '3 minutes',t+n*interval '3 minutes'+interval '60 seconds');
  if (v->>'xp')::integer<>0 then raise exception 'excess XP'; end if;
 end loop;
 labels:=labels||jsonb_build_array('nine_additional_workouts_zero_XP');
 v:=public.ritmo_my_summary();
 if (v->>'total_xp')::integer<>125 or (v->>'rewarded_workouts')::integer<>2 then raise exception 'daily cap'; end if;
 labels:=labels||jsonb_build_array('daily_limit_125_XP');
 seen:=false;begin
  insert into public.ritmo_xp_ledger(event_id,user_id,xp_day,xp) values(gen_random_uuid(),a,current_date,100);
 exception when insufficient_privilege then seen:=true;end;
 if not seen then raise exception 'direct XP write allowed';end if;
 labels:=labels||jsonb_build_array('direct_XP_write_denied');
 seen:=false;begin perform public.ritmo_submit_workout(gen_random_uuid(),t,t+interval '60 seconds');exception when invalid_parameter_value then seen:=true;end;
 if not seen then raise exception 'overlap allowed';end if;
 labels:=labels||jsonb_build_array('overlapping_session_rejected');
 seen:=false;begin perform public.ritmo_submit_workout(gen_random_uuid(),now(),now()+interval '10 minutes');exception when invalid_parameter_value then seen:=true;end;
 if not seen then raise exception 'future allowed';end if;
 labels:=labels||jsonb_build_array('future_completion_rejected');
 seen:=false;begin perform public.ritmo_submit_workout(gen_random_uuid(),now()-interval '8 days',now()-interval '8 days'+interval '60 seconds');exception when invalid_parameter_value then seen:=true;end;
 if not seen then raise exception 'old allowed';end if;
 labels:=labels||jsonb_build_array('offline_event_older_than_7_days_rejected');
 perform set_config('role','none',true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',b,'session_id',sb,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 select count(*) into n from public.ritmo_profiles where user_id=a;if n<>0 then raise exception 'cross profile';end if;
 labels:=labels||jsonb_build_array('RLS_hides_other_profile');
 select count(*) into n from public.ritmo_workout_events where user_id=a;if n<>0 then raise exception 'cross events';end if;
 labels:=labels||jsonb_build_array('RLS_hides_other_events');
 select count(*) into n from public.ritmo_xp_ledger where user_id=a;if n<>0 then raise exception 'cross XP';end if;
 labels:=labels||jsonb_build_array('RLS_hides_other_XP');
 seen:=false;begin perform public.ritmo_submit_workout(eid,t,t+interval '60 seconds');exception when invalid_parameter_value then seen:=true;end;
 if not seen then raise exception 'stolen UUID';end if;
 labels:=labels||jsonb_build_array('UUID_cannot_be_claimed_by_other_user');
 perform set_config('role','none',true);
 -- Administrative historical fixtures verify period cutoffs, not retroactive rewards from the app.
 for n in 0..1 loop
  eid:=gen_random_uuid();
  t:=case n when 0 then date_trunc('month',now() at time zone 'UTC') at time zone 'UTC'-interval '1 day' else date_trunc('week',now() at time zone 'UTC') at time zone 'UTC'-interval '1 day' end;
  insert into public.ritmo_workout_events(event_id,user_id,started_at,completed_at,xp_day) values(eid,a,t,t+interval '60 seconds',(t at time zone 'UTC')::date);
  insert into public.ritmo_xp_ledger(event_id,user_id,xp_day,xp) values(eid,a,(t at time zone 'UTC')::date,100);
 end loop;
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 v:=public.ritmo_ranking('weekly',10);if (v->'me'->>'xp')::integer<>(case when base_day>=date_trunc('week',now() at time zone 'UTC')::date then 125 else 0 end) then raise exception 'weekly period';end if;
 labels:=labels||jsonb_build_array('weekly_period_cutoff');
 v:=public.ritmo_ranking('all',100);if (v->'me'->>'xp')::integer<>325 then raise exception 'overall period';end if;
 labels:=labels||jsonb_build_array('overall_period_and_own_position');
 month_xp:=(case when base_day>=date_trunc('month',now() at time zone 'UTC')::date then 125 else 0 end)+case when (date_trunc('week',now() at time zone 'UTC')-interval '1 day')>=date_trunc('month',now() at time zone 'UTC') then 100 else 0 end;
 v:=public.ritmo_ranking('monthly',100);if (v->'me'->>'xp')::integer<>month_xp then raise exception 'monthly period';end if;
 labels:=labels||jsonb_build_array('monthly_period_cutoff');
 if v::text like '%user_id%' or v::text like '%email%' or v::text like '%started_at%' then raise exception 'private ranking data';end if;
 labels:=labels||jsonb_build_array('public_projection_omits_private_data');
 perform public.ritmo_save_profile('TxA_'||left(a::text,8),false);
 v:=public.ritmo_ranking('all',10);if v->'me'<>'null'::jsonb then raise exception 'optout visible';end if;
 labels:=labels||jsonb_build_array('privacy_opt_out_removes_user');
 perform set_config('role','none',true);
 delete from auth.sessions where id=sa;
 perform set_config('role','authenticated',true);
 seen:=false;begin perform public.ritmo_my_summary();exception when invalid_authorization_specification then seen:=true;end;
 if not seen then raise exception 'revoked session';end if;
 labels:=labels||jsonb_build_array('revoked_session_rejected');
 perform set_config('role','none',true);
 delete from auth.users where id=a;
 select count(*) into n from public.ritmo_profiles where user_id=a;if n<>0 then raise exception 'profile cascade';end if;
 labels:=labels||jsonb_build_array('deletion_cascades_profile');
 select count(*) into n from public.ritmo_workout_events where user_id=a;if n<>0 then raise exception 'event cascade';end if;
 labels:=labels||jsonb_build_array('deletion_cascades_events');
 select count(*) into n from public.ritmo_xp_ledger where user_id=a;if n<>0 then raise exception 'XP cascade';end if;
 labels:=labels||jsonb_build_array('deletion_cascades_XP');
 perform set_config('request.jwt.claims',jsonb_build_object('sub',a,'session_id',sa,'role','authenticated')::text,true);
 perform set_config('role','authenticated',true);
 seen:=false;begin perform public.ritmo_get_profile();exception when invalid_authorization_specification then seen:=true;end;
 if not seen then raise exception 'deleted account accepted';end if;
 labels:=labels||jsonb_build_array('deleted_user_rejected');
 perform set_config('role','none',true);perform set_config('request.jwt.claims','{}',true);perform set_config('role','anon',true);
 v:=public.ritmo_ranking('all',10);if v->'me'<>'null'::jsonb then raise exception 'guest identity';end if;
 labels:=labels||jsonb_build_array('guest_only_reads_public_projection');
 seen:=false;begin perform public.ritmo_my_summary();exception when insufficient_privilege then seen:=true;end;
 if not seen then raise exception 'guest private access';end if;
 labels:=labels||jsonb_build_array('guest_cannot_read_private_summary');
 perform set_config('role','none',true);
 perform set_config('ritmo.test_results',jsonb_build_object('passed',jsonb_array_length(labels),'checks',labels,'fixture_type','synthetic Auth rows and JWT claims, no real HTTP login','rollback',true)::text,true);
end $test$;
select current_setting('ritmo.test_results')::jsonb as hosted_transaction_result;
rollback;
